name: pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
         python-version: '3.x'
      - name: Train model
        run: |
          pip install -r requirements.txt
          pip install --upgrade pip
          python train.py